### ISSUE TITLE
Error: Dynamic require of "./workerBundle" is not supported

### ISSUE THREAD

**Issue by scriptex** [Aeolun/react-diff-viewer-continued#84]
Hello and thank you for your continued support on this library.

Since you published the last version 4.1.2 or maybe since 4.1.0 I've been experiencing an issue with the Worker.

The error being thrown is 

```
[Error] Error: Dynamic require of "./workerBundle" is not supported
```

And this error results in 

```
Unhandled Promise Rejection: DataCloneError: The object can not be cloned.
```

which is kind of expected.

These errors result in empty diffs which is a breaking change.

I see you have unpublished commits related to how the Worker is being bundled and used so I am guessing somebody else also experienced similar issues.

Is there any ETA on a fix for this?

FWIW I am using Vite v6.4.1. and I cannot switch to a different bundler.

Might I suggest a workaround for the future - it might be a good idea to add a setting which completely disables usage of Workers in favor of the [`fallback()` function](https://github.com/Aeolun/react-diff-viewer-continued/blob/69787220dd29300351c10d7bbdf1d05ab7b3aaf5/src/compute-lines.ts#L693)

**Comment by joliss** [comment]
I'm similarly getting a "Cannot find module .../workerBundle" error with Next 15 and Webpack:

    ⨯ ["Error: Cannot find module '.../node_modules/.pnpm/react-diff-viewer-continued@4.1.2_@types+react@19.1.13_react-dom@19.2.3_react@19.2.3__react@19.2.3/node_modules/react-diff-viewer-continued/lib/esm/src/workerBundle' imported from .../node_modules/.pnpm/react-diff-viewer-continued@4.1.2_@types+react@19.1.13_react-dom@19.2.3_react@19.2.3__react@19.2.3/node_modules/react-diff-viewer-continued/lib/esm/src/compute-lines.js]

As a workaround, downgrading to `"react-diff-viewer-continued": "=4.0.6"` fixes the issue for me.

*Edit:* It's working fine in the latest v4.2.2 now.

**Comment by Aeolun** [comment]
It is now possible to completely disable the worker with a property `disableWorker`, this should prevent both loading the file and will automatically fall back to the fallback version. I'm not sure if this problem still existed in v4.2.0 in the first place, but if it ever goes wrong again in the future the whole thing can just be turned off.
